language: csharp
solution: MimeKit.Net45.sln
install:
  - nuget restore MimeKit.Net45.sln
script:
  - msbuild /p:Configuration=Debug MimeKit.Net45.sln
  - mono ./packages/NUnit.ConsoleRunner.3.11.1/tools/nunit3-console.exe UnitTests/bin/Debug/UnitTests.dll
